name: ERPNext App Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis-cache:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis-queue:
        image: redis:6
        ports:
          - 6380:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis-socketio:
        image: redis:6
        ports:
          - 6381:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Bench
        run: pip install frappe-bench

      - name: Init Bench
        run: bench init --frappe-branch v15.79.0 frappe-bench

      - name: Get ERPNext & App
        run: |
          cd frappe-bench
          bench get-app --branch v15.79.0 erpnext --skip-assets
          bench get-app https://github.com/KTA-Endustri-Sistemleri/negative_stock_control.git --skip-assets
          printf "\nnegative_stock_control\n" >> sites/apps.txt

      - name: New Site
        run: |
          cd frappe-bench
          bench new-site karamalli.localhost --mariadb-root-password root --admin-password admin --no-mariadb-socket

      - name: Install ERPNext
        run: |
          cd frappe-bench
          bench --site karamalli.localhost install-app erpnext

      - name: Install Negative Stock Control
        run: |
          cd frappe-bench
          bench --site karamalli.localhost install-app negative_stock_control
          bench --site karamalli.localhost migrate

      - name: Run Tests
        run: |
          cd frappe-bench
          bench --site karamalli.localhost run-tests --app negative_stock_control --verbose